version: '3.7'
services:
  api:
    container_name: jpm-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: jpm-api:lastest
    ports:
      - '8080:8080'
    environment:
      - TZ=Asia/Bangkok
